import { NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { db } from "@/lib/db";

// Check if code matches auto-generated format: XXXX-YYYYYYYY
// Where XXXX is first 4 chars of org ID, YYYYYYYY is last 8 chars of item ID
function parseAutoGeneratedCode(code: string): { orgPrefix: string; itemSuffix: string } | null {
  const match = code.match(/^([A-Z0-9]{4})-([A-Z0-9]{8})$/i);
  if (match) {
    return { orgPrefix: match[1].toUpperCase(), itemSuffix: match[2].toUpperCase() };
  }
  return null;
}

export async function GET(req: Request) {
  try {
    const session = await auth();
    if (!session?.user?.organizationId) {
      return NextResponse.json({ message: "Unauthorized" }, { status: 401 });
    }

    const { searchParams } = new URL(req.url);
    const code = searchParams.get("sku");

    if (!code) {
      return NextResponse.json({ message: "Code is required" }, { status: 400 });
    }

    // First, try to find by SKU (case-insensitive)
    let costume = await db.costumeItem.findFirst({
      where: {
        organizationId: session.user.organizationId,
        sku: { equals: code, mode: "insensitive" },
      },
      include: {
        category: { select: { name: true } },
        photos: {
          where: { type: "MAIN" },
          take: 1,
          select: { url: true },
        },
      },
    });

    // If not found by SKU, try parsing as auto-generated code
    if (!costume) {
      const parsed = parseAutoGeneratedCode(code);
      if (parsed) {
        // Verify org prefix matches
        const orgPrefix = session.user.organizationId.slice(0, 4).toUpperCase();
        if (parsed.orgPrefix === orgPrefix) {
          // Find items whose ID ends with the suffix
          costume = await db.costumeItem.findFirst({
            where: {
              organizationId: session.user.organizationId,
              id: { endsWith: parsed.itemSuffix.toLowerCase() },
            },
            include: {
              category: { select: { name: true } },
              photos: {
                where: { type: "MAIN" },
                take: 1,
                select: { url: true },
              },
            },
          });
        }
      }
    }

    if (!costume) {
      return NextResponse.json({ message: "Not found" }, { status: 404 });
    }

    return NextResponse.json({
      id: costume.id,
      name: costume.name,
      sku: costume.sku,
      status: costume.status,
      location: costume.location,
      category: costume.category,
      photos: costume.photos,
    });
  } catch (error) {
    console.error("Lookup error:", error);
    return NextResponse.json(
      { message: "Something went wrong" },
      { status: 500 }
    );
  }
}
